### ISSUE TITLE
No News ?

### ISSUE THREAD

**Issue by Darknior** [adventuregamestudio/scummvm#2] opened 2019-08-21 12:38 UTC
Two years from the last comit ...
Will some one always working on this port of AGS to ScummVM ?
It is really a good idea now scumm is working every where ...
There is also a preliminary SummVM retroarch core.
Thanks

**Comment by i30817** [comment] 2019-08-21 14:26
Probably not a good idea now.

AGS at the time had the idea that it was going to go break compatibility and put out a 'AGS4' engine, so the idea for this was '_just_ support AGS2 to AGS3.5 since it's going to be frozen'.


AFAICT (which is not much) it out that this was moderately controversial, and the main contributor was having some burnout, so things just kept getting added to AGS 3.5... and there are many many regressions still from earlier versions of the engine, so the effort to get out a 'final version' is, not exactly stalled, because there is admirable progression to deal with those ancient regressions, but needs more effort.
Currently the 'AGS4' branch is sort of abandoned for a year and the AGS3.5 branch is getting weekly commits still (even if it's frozen for new features, though multiple viewports got in).

I suspect that a scummvm origin new engine from scratch would have a uphill battle getting near the same compatibility (though maybe they'd be able to get better code eventually due to scummvm willingness to patch game scripts with runtime bytecode). In fact, AGS3.5 currently can't run many games from the age where they unwisely implemented dev extensions as compiled code instead of scripts (agslua.dll, agsfire.dll, etc etc etc, though at least there are stubs for steam and galaxy now), so it's a uphill effort still.

If you want AGS on other platforms, a better idea might be to do work to make it happen in Retroarch with a libretro port of the AGS 3.5 branch, much like the gamemaker engine there.

**Comment by Darknior** [comment] 2019-08-21 15:33
Ok thanks i understand.
We are on PI, with Retropie or Batocera. And want to play some AGS games.
Retropie has an old AGS engine already ported. And i try some games with it, only on keyboard and mouse, impossible to use a gamepad :(
It is important because it's to play on TV not on a computer.

I can try to compile AGS 3.5 last version on PI, but you write me some games with some compiled extention (agslua.dll, agsfire.dll, etc etc etc) will not working :(
Maybe some commercial games ?

I see there are some commercial games ... not easy to found all the best free games to play with AGS :)
I have think to buy some commercial games to use them on pi but if you write me some will not work i can't know it before testing :(

And i don't know any one interesting to port AGS in LIBRETRO but it is really a good idea :)

**Comment by ghost** [comment] 2019-08-21 15:49
IIRC the plan that we were having was to have ScummVM port complete with at least 3.2.1 or 3.3.* support. I think it is about done except particular functionality like savegames and maybe few API functions.
The problem of course is that since engine is being updated further someone would need to continiously update ScummVM port as well.

But this is kind of complicated further by dev team having contradicting opinion on whether to drop legacy support from AGS project itself or not. Note that we have brought this fork here at times when we were leaning towards dropping backwards compatibility from AGS and forgetting about it. In such case this ScummVM port could serve as a primary tool to run old AGS games. But now there's an ongoing discussion about *maybe* continuing to keep old support in AGS and make ags engine a modular system where, roughly speaking, each large set of functionality has its own "game logic" module.
So... idk.
(EDIT: frankly, I am not participating in this discussion, and not much eager to work on ags or this port further anymore)

PS. BTW AGS 3.5.0 is practically out. Personally I do not see legacy game regressions as a big problem: that happened before each time a major feature set added, and will eventually be dealt with, maybe in following patches.

**Comment by Darknior** [comment] 2019-08-21 17:41
> to keep old support in AGS and make ags engine a modular system 

It can really cool if it can be officially added to ScimmVM as an game engine like any other, and we can add to our set all the old AGS games :)
Like the remake of King Quest in VGA and all other games :)
One day maybe ...

**Comment by i30817** [comment] 2019-08-21 18:49
Many commercial games 'just work' if you compile AGS3.5 with the builtin plugins enable since the stubs for galaxy and steam were added to the engine plugins (agslua replacement doesn't work thou), and to a lesser degree the wadjeteye plugin i forget the name. I've found a exception (Sumatra Fate of Yendi) where there is a bug with the new pathfinder that breaks a scripted transition and you can't progress (the older pathfinder cheated).

It's mostly older games using the plugin dlls that are broken and some high profile later games from the Kathy Rain studio because they added/changed some code.

Now compiling it for the Raspberry Pi... that is likely to be broken/painful, though it's a worthy goal. As a libretro engine, it would be nice to have optional controller support too.

I also sort of want the engine supporting data on read only places with the writes redirected to the system save dir (to be able to play the games on compressed/readonly filesystems). Nearly all Tierra/AGDI games use some extra files writes for some functionality and then crash on a readonly filesystem.

**Comment by ghost** [comment] 2019-08-21 20:58
> I also sort of want the engine supporting data on read only places with the writes redirected to the system save dir (to be able to play the games on compressed/readonly filesystems). Nearly all Tierra/AGDI games use some extra files writes for some functionality and then crash on a readonly filesystem.

I remember we had this discussion:
https://github.com/adventuregamestudio/ags/issues/799#issuecomment-497318552
If I understood correctly, currently this works with manual configuration, and point is in implementing automatic remap.

**Comment by i30817** [comment] 2019-08-22 04:35
Oh right, yes, manual configuration 'works' but the fact it's not a default, or there is a way to change the default from 'game dir' to 'system dir' on the cfg means the games aren't really portable on read only filesystems.

If i transfer the filesystem to another computer, or login with another user, a hardcoded shared_data_dir on the config would mean the writes failed again and if the configs were in a readonly filesystem on the game dir, it would be even worse.

In essence i guess i'm asking for a setting I can toggle on on all cfgs and forget where 'shared_data_dir=system_dir' with a symbolic name (instead of the implicit symbolic default, shared_data_dir=game_dir or a explicit path), so that games that want to be cute with file IO can all redirect to a appropriately writable dir everytime.

I'm unsure if such a setting should be default, there may be games that actually depend on reading a file they bundled with the release (instead of writing it if not there then reading it like AGDI games), and this would probably break them if made default. I didn't find any i think thou i've not been looking (as opposed to looking for games that break on readonly filesystems, which is how i found nearly all AGDI games do). And ofc Steam and Windows 'encourages' modern games to not write to their dirs.

**Comment by ghost** [comment] 2019-08-22 10:02
@i30817 could you please post this in the linked thread? I am afraid I did not understand everything you said, so will have to look more closely later.

**Comment by i30817** [comment] 2019-08-22 10:55
Yeah, it's done.

**Comment by ericoporto** [comment] 2021-06-18 21:03
Just for information while the code here did not get finished, an official ScummVM port was done by porting over from ags3

https://www.scummvm.org/news/20210404/
https://www.adventuregamestudio.co.uk/forums/index.php?topic=58591.0

So this could be closed.

A suggestion, a new branch named "home" could be created with just a single README.md file explaining this, and made default, to help people finding this code, and the repository could be marked as archived.

**Comment by ivan-mogilko** [comment] 2022-04-16 22:48
Ok, so,
* make new branch (?);
* make readme;
* archive the repository, to have a reference of an older refactor/port attempt.

**Comment by ivan-mogilko** [comment] 2022-04-16 23:00
BTW, is this ok to rename the repository? We might rename it to something, just in case someone from the organization would like to fork an official scummvm repo later.

Another option: if it's possible to change the upstream reference, then we could create a separate branch for an old port (e.g. `fuzzie-ags`), and change upstream to the scummvm org repo. This way we have both an "archived" branch with an old port, and the repository is available if someone would like to use it to make pull requests into scummvm.

**Comment by ericoporto** [comment] 2022-04-16 23:39
perhaps just setting the new fuzzie-ags branch as default and place a readme to explain what happened.

the suggestion of archiving is just to clearly explain to people to not expect any changes in the code here.

I think renaming the repository is fine.

> if it's possible to change the upstream reference

Uhm, I think while it's possible to do this locally, I don't know how to do this in GitHub interface for the remote repository itself.

**Comment by ivan-mogilko** [comment] 2023-12-25 00:15
Renamed the repository, will archive it.

**Closed as completed by ivan-mogilko** 2023-12-25 00:15 UTC
